### ISSUE TITLE
Debugger not working when attaching to IIS process

### ISSUE THREAD

**Issue by chriszimmerman** [JetBrains/resharper-unity#1007]
JetBrains Rider 2018.3.1
Build #RD-183.5253.26, built on December 26, 2018
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Hello,

When I try to attach to the IIS process to debug my web app, I get the below message and the app seems to freeze.

```
Input/Output redirection disabled: Debugger is attached to an already running process
"C:\Program Files\JetBrains\JetBrains Rider 2018.3\bin\runnerw64.exe" "C:\Program Files\JetBrains\JetBrains Rider 2018.3\lib\ReSharperHost\JetBrains.Debugger.Worker64c.exe" --mode=client --frontend-port=51818 "--plugins=C:\Program Files\JetBrains\JetBrains Rider 2018.3\plugins\rider-unity\dotnetDebuggerWorker"
```

Looking in the `idea` log file, this is the most recent meaningful-looking output that happens while experiencing the issue:

```
08:31:43.872 | INFO  | DotNetCoreAttachProviderBase   | .NET Core runtime does have info about process with pid 15548
08:31:43.873 | INFO  | DotNetCoreAttachProviderBase   | .NET Core attach provider has info about 2 processes
08:31:43.873 | INFO  | DotNetCoreAttachProviderBase   | .NET Core runtime does have info about process with pid 22268
08:31:43.873 | INFO  | DotNetCoreAttachProviderBase   | .NET Core attach provider has info about 2 processes
08:31:43.873 | INFO  | DotNetCoreAttachProviderBase   | .NET Core attach provider has info about 2 processes
08:31:45.814 | INFO  | RiderEnvironment               | %RESHARPER_HOST_BIN% is not set
08:31:45.815 | INFO  | RiderEnvironment               | JetBrains.Debugger.Worker64c.exe found at C:\Program Files\JetBrains\JetBrains Rider 2018.3\lib\ReSharperHost\JetBrains.Debugger.Worker64c.exe (bundled to IDEA)
08:31:46.449 | INFO  | FrontendTextControlHost        | Editor released. com.intellij.openapi.editor.impl.EditorImpl@2efe2c9e
08:31:46.453 | INFO  | FrontendTextControlHost        | Editor released. com.intellij.openapi.editor.impl.EditorImpl@2c664b3e
08:33:45.826 | WARN  | BaseOSProcessHandler           | Process hasn't generated any output for a long time.
If it's a long-running mostly idle daemon process, consider overriding OSProcessHandler#readerOptions with 'BaseOutputReader.Options.forMostlySilentProcess()' to reduce CPU usage.
Command line: "C:\Program Files\JetBrains\JetBrains Rider 2018.3\bin\runnerw64.exe" "C:\Program Files\JetBrains\JetBrains Rider 2018.3\lib\ReSharperHost\JetBrains.Debugger.Worker64c.exe" --mode=client --frontend-port=52438 "--plugins=C:\Program Files\JetBrains\JetBrains Rider 2018.3\plugins\rider-unity\dotnetDebuggerWorker"
java.lang.Throwable: Process creation:
	at com.intellij.execution.process.BaseOSProcessHandler.<init>(BaseOSProcessHandler.java:34)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:89)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:44)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:49)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:57)
	at com.jetbrains.rider.run.IDotNetDebugProfileState$DefaultImpls.startDebuggerWorker(IDotNetDebugProfileState.kt:41)
	at com.jetbrains.rider.run.DebugProfileStateBase.startDebuggerWorker(DebugProfileStateBase.kt:14)
	at com.jetbrains.rider.debugger.RiderDebugRunner$prepareModelAndProcess$2.consume(RiderDebugRunner.kt:106)
	at com.jetbrains.rider.debugger.RiderDebugRunner$prepareModelAndProcess$2.consume(RiderDebugRunner.kt:46)
	at org.jetbrains.concurrency.Promise.lambda$done$0(Promise.java:90)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$whenComplete$1.accept(AsyncPromise.kt:54)
	at org.jetbrains.concurrency.AsyncPromise$onSuccess$whenComplete$1.accept(AsyncPromise.kt:12)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at org.jetbrains.concurrency.AsyncPromise.setResult(AsyncPromise.kt:117)
	at com.jetbrains.rider.run.msNet.MsNetAttachProfileState$createWorkerRunCmd$1.invoke(MsNetAttachProfileState.kt:28)
	at com.jetbrains.rider.run.msNet.MsNetAttachProfileState$createWorkerRunCmd$1.invoke(MsNetAttachProfileState.kt:17)
	at com.jetbrains.rider.util.reactive.Signal.fire(Signal.kt:28)
	at com.jetbrains.rider.util.reactive.OptProperty.set(Property.kt:36)
	at com.jetbrains.rider.framework.impl.RdCall$onWireReceived$3.invoke(RdTask.kt:113)
	at com.jetbrains.rider.framework.impl.RdCall$onWireReceived$3.invoke(RdTask.kt:50)
	at com.jetbrains.rdclient.protocol.RdDispatcher.a(RdDispatcher.kt:85)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:14)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:19)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
08:34:35.354 | INFO  | ServerPollingManager           | Timer fired
08:34:35.354 | INFO  | ServerEventManager             | triggering ALL events
08:34:35.354 | INFO  | ServerEventManager             | triggering event: BUILDS_CHANGED
08:34:35.354 | INFO  | ServerEventManager             | triggering event: PULL_REQUESTS_CHANGED
08:34:35.354 | INFO  | ServerEventManager             | triggering event: WORK_ITEMS_CHANGED
```

Please let me know if I can provide any other information to help out. Thanks for taking the time to look at this.

**Comment by citizenmatt** [comment]
Please could you raise the issue here: https://youtrack.jetbrains.com/newIssue?project=RIDER

This project is for the Unity support in Rider, and unfortunately we're not the best people to try and help with IIS + debugging. If you raise the issue in YouTrack, it will get routed to the correct people and you'll get notifications of updates, etc.

**Comment by chriszimmerman** [comment]
You got it. Thanks for pointing me to the right folks!
