### ISSUE TITLE
Unity 2019.1.0b3 crash on Attach debugger and Play.

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#1045]
just attach rider to unity, press play, boom. VS works fine.
It crashes even without our EditorPlugin.
```
Reloading assemblies for play mode.
Begin MonoManager ReloadAssembly
Receiving unhandled NULL exception
Obtained 12 stack frames.
#0  0x0000014a7095bb in mono_image_get_assembly
#1  0x0000014a6421cb in assembly_unload
#2  0x0000014a75c591 in mono_profiler_raise_assembly_unloading
#3  0x0000014a6da1e2 in mono_assembly_close_except_image_pools
#4  0x0000014a6d3bf9 in mono_domain_free
#5  0x0000014a6d14e4 in unload_thread_main
#6  0x0000014a7697bc in start_wrapper
#7  0x0000014a7dd223 in GC_inner_start_routine
#8  0x0000014a7dd1b8 in GC_start_routine
#9  0x007fff6f4b133d in _pthread_body
#10 0x007fff6f4b42a7 in _pthread_start
#11 0x007fff6f4b0425 in thread_start
```

**Comment by van800** [comment]
Fixed in Unity https://github.com/Unity-Technologies/mono/pull/1141
