### ISSUE TITLE
Attach to process doesn't show up

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#1454]
10:39:09.069 | ERROR | Task                           | Illegal char <"> at index 25: C:Workcom.unity.ide.rider"
java.nio.file.InvalidPathException: Illegal char <"> at index 25: C:Workcom.unity.ide.rider"
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.jetbrains.rider.plugins.unity.run.UnityRunUtil.getProjectNameFromPath(UnityRunUtil.kt:194)
	at com.jetbrains.rider.plugins.unity.run.UnityRunUtil.getProjectNameFromCommandLine(UnityRunUtil.kt:117)
	at com.jetbrains.rider.plugins.unity.run.UnityRunUtil.getUnityProcessProjectNames(UnityRunUtil.kt:83)
	at com.jetbrains.rider.plugins.unity.run.UnityRunUtil.getUnityProcessProjectName(UnityRunUtil.kt:63)
	at com.jetbrains.rider.plugins.unity.run.attach.UnityLocalAttachProcessDebuggerProvider.getAvailableDebuggers(UnityLocalAttachProcessDebuggerProvider.kt:20)
	at com.intellij.xdebugger.impl.actions.AttachToProcessActionBase.doCollectAttachProcessItems(AttachToProcessActionBase.java:268)
	at com.intellij.xdebugger.impl.actions.AttachToProcessActionBase.collectAttachProcessItems(AttachToProcessActionBase.java:247)
	at com.intellij.xdebugger.impl.actions.AttachToProcessActionBase.getTopLevelItems(AttachToProcessActionBase.java:144)
	at com.intellij.xdebugger.impl.actions.AttachToProcessActionBase$1.run(AttachToProcessActionBase.java:91)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:402)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:402)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by van800** [comment]
Unity process was started with 
```"F:\progra\2019.2.12f1\Editor\Unity.exe" -projectPath "C:\Work\com.unity.ide.rider\"```

**Comment by van800** [comment]
When I kill the Unity process - Attach to process starts showing list of processes as normal.
