### ISSUE TITLE
UnityCachesFinder looks for caches in a hardcoded path

### ISSUE THREAD

**Issue by nick-morhun** [JetBrains/resharper-unity#1766]
I have my Unity package caches moved according to https://docs.unity3d.com/Manual/upm-cache.html. And today I noticed in my idea.log exceptions like this:

```
2020-07-21 09:54:42,339 | ERROR | UnityCachesFinder              | Error looking for registry cache location: C:\Users\nickm\AppData\Local\Unity\cache\packages/packages.unity.com
java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged
	at com.intellij.openapi.diagnostic.Logger.checkException(Logger.java:198)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:88)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:168)
	at com.jetbrains.rider.plugins.unity.util.UnityCachesFinder$Companion.findPackagesCache(UnityCachesFinder.kt:53)
	at com.jetbrains.rider.plugins.unity.util.UnityCachesFinder$Companion.getPackagesCacheFolder(UnityCachesFinder.kt:33)
	at com.jetbrains.rider.plugins.unity.packageManager.PackageManager.getRegistryPackage(PackageManager.kt:340)
	at com.jetbrains.rider.plugins.unity.packageManager.PackageManager.getPackageData(PackageManager.kt:268)
	at com.jetbrains.rider.plugins.unity.packageManager.PackageManager.getPackages(PackageManager.kt:178)
	at com.jetbrains.rider.plugins.unity.packageManager.PackageManager.access$getPackages(PackageManager.kt:43)
	at com.jetbrains.rider.plugins.unity.packageManager.PackageManager$refreshAndNotify$1.call(PackageManager.kt:123)
	at com.jetbrains.rider.plugins.unity.packageManager.PackageManager$refreshAndNotify$1.call(PackageManager.kt:43)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:472)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$2(NonBlockingReadActionImpl.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:437)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$0(NonBlockingReadActionImpl.java:370)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:193)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.EmptyProgressIndicator.checkCanceled(EmptyProgressIndicator.java:84)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.checkCancelledEvenWithPCEDisabled(ProgressIndicatorUtils.java:363)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:321)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:316)
	at com.intellij.openapi.vfs.DiskQueryRelay.accessDiskWithCheckCanceled(DiskQueryRelay.java:50)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.getAttributes(LocalFileSystemBase.java:689)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.isDirectory(LocalFileSystemBase.java:107)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.findChild(VirtualDirectoryImpl.java:84)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.refreshAndFindChild(VirtualDirectoryImpl.java:297)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.refreshAndFindFileByPath(VfsImplUtil.java:115)
	at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.refreshAndFindFileByPath(LocalFileSystemBase.java:57)
	at com.intellij.openapi.vfs.VfsUtil.findFile(VfsUtil.java:215)
	at com.intellij.openapi.vfs.VfsUtil.findFile(VfsUtil.java:202)
	at com.jetbrains.rider.plugins.unity.util.UnityCachesFinder$Companion.findPackagesCache(UnityCachesFinder.kt:50)
	... 28 more
```

I can see the problem here [UnityCachesFinder](https://github.com/JetBrains/resharper-unity/blob/67d2a82172c95b9d032a5cac448a6cc4a0c0243e/rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/util/UnityCachesFinder.kt#L36).

**Comment by van800** [comment]
Thank you for the report. 
Is that env. var. global in your case of only for Unity process?

**Comment by citizenmatt** [comment]
Can you also confirm the version of Unity please?

**Comment by citizenmatt** [comment]
Actually, this particular error message isn't the root cause of a problem. An exception is being thrown to indicate that things have changed and the operation should be cancelled. It's not showing that the files can't be found, etc. Are you seeing any problems with the Packages view of the Unity Explorer?

That's not to say there aren't problems here. We should be looking at the `UPM_` environment variables, and I'm not sure why we've ended up in this fallback code - since Unity 2018.3, all packages are cached under `Library/PackageCache`, so we shouldn't be looking in the global cache at all, unless you're on an older version of Unity.

**Comment by nick-morhun** [comment]
> 
> 
> Thank you for the report.
> Is that env. var. global in your case of only for Unity process?

It's Windows system variables

**Comment by nick-morhun** [comment]
Unity version is 2019.2, plugin version 2.0.5

**Comment by nick-morhun** [comment]
> 
> 
> Are you seeing any problems with the Packages view of the Unity Explorer?

No it takes packages from the project's cache.
