### ISSUE TITLE
Test runner hangs

### ISSUE THREAD

**Issue by MDzyga** [JetBrains/resharper-unity#2132]
Hi,
I updated my VS Enterprise and Resharper to the latest version. After itI have a problem with executing unit tests because Test Runner hangs.

Solution: .NET 5.0
VS Enterprise 2019: 16.10.4
R# version: 2021.1.4 (the same issue using 2021.1.5)

Logs:

```
2021.07.22 09:51:22.461    WARN Test agent \AppData\Local\JetBrains\Installations\ReSharperPlatformVs16_81291753_000\TestRunner\netcoreapp2.0\ReSharperTestRunner64.exe:20808 is probably hanging
2021.07.22 09:51:25.374    WARN Test agent \AppData\Local\JetBrains\Installations\ReSharperPlatformVs16_81291753_000\TestRunner\netcoreapp2.0\ReSharperTestRunner64.exe:3060 is probably hanging
2021.07.22 09:51:25.809   ERROR Can't kill process `System.Diagnostics.Process (ReSharperTestRunner64)` in 00:00:02 ms

--- EXCEPTION #1/1 [LoggerException]
Message = “Can't kill process `System.Diagnostics.Process (ReSharperTestRunner64)` in 00:00:02 ms”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.ILoggerEx.LogMessage[T1,T2](ILogger this, LoggingLevel level, String message, T1 t1, T2 t2)
     at JetBrains.ReSharper.UnitTestFramework.Processes.PreparedProcess.Kill()
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerRunStrategy.DisposableAgentWrapper.Dispose()
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerRunStrategy.<Run>d__16.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<RunTests>d__8.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerAgentManager.BoundTestRunnerAgent.<RunSafe>d__11.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at JetBrains.ReSharper.UnitTestFramework.Extensions.TaskExtensions.<ThrowIf>d__14`2.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Threading.Tasks.TaskFactory.CompleteOnInvokePromise.Invoke(Task completingTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at JetBrains.ReSharper.UnitTestFramework.Extensions.TaskExtensions.<ToEmptyTask>d__13.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
     at JetBrains.ReSharper.UnitTestFramework.Extensions.TaskExtensions.<CancelIf>d__15.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Threading.Tasks.TaskFactory.CompleteOnInvokePromise.Invoke(Task completingTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<<RunTests>b__8_2>d.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.ServerMessageBroker.<SendMessage>d__2.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.RunAction(Object state)
     at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
     at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
”

2021.07.22 09:51:28.656   ERROR Can't kill process `System.Diagnostics.Process (ReSharperTestRunner64)` in 00:00:02 ms

--- EXCEPTION #1/1 [LoggerException]
Message = “Can't kill process `System.Diagnostics.Process (ReSharperTestRunner64)` in 00:00:02 ms”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.ILoggerEx.LogMessage[T1,T2](ILogger this, LoggingLevel level, String message, T1 t1, T2 t2)
     at JetBrains.ReSharper.UnitTestFramework.Processes.PreparedProcess.Kill()
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerRunStrategy.DisposableAgentWrapper.Dispose()
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerRunStrategy.<Run>d__16.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<RunTests>d__8.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerAgentManager.BoundTestRunnerAgent.<RunSafe>d__11.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at JetBrains.ReSharper.UnitTestFramework.Extensions.TaskExtensions.<ThrowIf>d__14`2.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Threading.Tasks.TaskFactory.CompleteOnInvokePromise.Invoke(Task completingTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at JetBrains.ReSharper.UnitTestFramework.Extensions.TaskExtensions.<ToEmptyTask>d__13.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
     at JetBrains.ReSharper.UnitTestFramework.Extensions.TaskExtensions.<CancelIf>d__15.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Threading.Tasks.TaskFactory.CompleteOnInvokePromise.Invoke(Task completingTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<<RunTests>b__8_2>d.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(TResult result)
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(Task`1 completedTask)
     at JetBrains.ReSharper.UnitTestFramework.TestRunner.ServerMessageBroker.<SendMessage>d__2.MoveNext()
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
     at System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.RunAction(Object state)
     at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
     at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
”

2021.07.22 09:51:35.237    WARN Process AppData\Local\JetBrains\Installations\ReSharperPlatformVs16_81291753_000\TestRunner\netcoreapp2.0\ReSharperTestRunner64.exe:20808 exited with code '-1':
Sent MSH|^~\&|SendingApplication|SendingOrganization|DiagCORECOU-DUROUXG-L2||201903221516||RSP^K11^RSP_K11|M201903221516430004|P|2.5||||||UNICODE UTF-8
MSA|AA|M202101111234370023
QAK|Q202101111234370023|OK
QPD|WOS^Work Order Step|Q202101111234370023|321123
PID|1||PatientID||^^^^^^||
SPM|1|321123|null|SWAB^swab|||||||P||||||201903151051
ORC|NW|OrderNumber|||IP||||201903151051
TQ1|1||||||||R
OBR|1|2342343536||GI|||||201910071745||A



2021.07.22 09:51:41.633    WARN Process \AppData\Local\JetBrains\Installations\ReSharperPlatformVs16_81291753_000\TestRunner\netcoreapp2.0\ReSharperTestRunner64.exe:3060 exited with code '-1'.
```

**Comment by van800** [comment]
Hey! This hang is unrelated to this Unity plugin. For ReSharper we do not provide any specific support for Unuty unit testing. Please report this issue to ReSharper team.
