### ISSUE TITLE
As-you-type event function completion breaks if in wrong class type

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/resharper-unity#420]
E.g. if trying to type and complete `Awake` in a `struct` that derives from `MonoBehaviour`, the completion fails with an exception. Yes, this is invalid code, but we should fail gracefully, without an exception.

<details>
<summary>AssertionException: Generation is not available</summary>

```
Generation is not available

--- EXCEPTION #1/2 [AssertionException]
Message = “Generation is not available”
ExceptionPath = Root.InnerException
ClassName = JetBrains.Util.Assertion+AssertionException
HResult = COR_E_EXCEPTION=80131500
Source = JetBrains.Platform.RdCore
StackTraceString = “
  at JetBrains.Util.Assertion.Fail (System.String message) [0x00006] in <0e626f36971646f391be51717a3fc4b9>:0 
    at JetBrains.Util.Assertion.Assert (System.Boolean condition, System.String message) [0x00003] in <0e626f36971646f391be51717a3fc4b9>:0 
    at JetBrains.ReSharper.Feature.Services.Generate.Workflows.GenerateCodeWorkflowBase.ExecuteNonInteractive (System.String kind, JetBrains.ProjectModel.ISolution solution, JetBrains.TextControl.ITextControl textControl, JetBrains.ReSharper.Psi.PsiLanguageType languageType, JetBrains.Application.Progress.IProgressIndicator progress, System.Action`1[T] configureContext, System.Action`1[T] onCompleted) [0x00022] in <fa3055d36e9b44258d3aec143e6da8b4>:0 
    at JetBrains.ReSharper.Plugins.Unity.Feature.Services.CodeCompletion.UnityEventFunctionBehavior.Accept (JetBrains.TextControl.ITextControl textControl, JetBrains.DocumentModel.IRangeMarker rangeMarker, JetBrains.ProjectModel.ISolution solution) [0x00153] in <62d4493553c644dc94c24ad0acbef862>:0 
    at JetBrains.ReSharper.Plugins.Unity.Feature.Services.CodeCompletion.UnityEventFunctionBehavior.Accept (JetBrains.TextControl.ITextControl textControl, JetBrains.DocumentModel.DocumentRange nameRange, JetBrains.ReSharper.Feature.Services.Lookup.LookupItemInsertType lookupItemInsertType, JetBrains.ReSharper.Feature.Services.Lookup.Suffix suffix, JetBrains.ProjectModel.ISolution solution, System.Boolean keepCaretStill) [0x00007] in <62d4493553c644dc94c24ad0acbef862>:0 
    at JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.AspectLookupItems.BaseInfrastructure.LookupItem`1[TInfo].Accept (JetBrains.TextControl.ITextControl textControl, JetBrains.DocumentModel.DocumentRange nameRange, JetBrains.ReSharper.Feature.Services.Lookup.LookupItemInsertType insertType, JetBrains.ReSharper.Feature.Services.Lookup.Suffix suffix, JetBrains.ProjectModel.ISolution solution, System.Boolean keepCaretStill) [0x00006] in <fa3055d36e9b44258d3aec143e6da8b4>:0 
    at JetBrains.ReSharper.Feature.Services.CodeCompletion.CombinedLookupItem.CompleteItems (System.Collections.Generic.List`1[T] items, JetBrains.ReSharper.Psi.IPsiServices psiServices, JetBrains.TextControl.ITextControl textControl, JetBrains.DocumentModel.DocumentRange nameRange, JetBrains.ReSharper.Feature.Services.Lookup.LookupItemInsertType insertType, JetBrains.ReSharper.Feature.Services.Lookup.Suffix suffix, JetBrains.ProjectModel.ISolution solution, System.Boolean keepCaretStill, System.IDisposable batchTextChange) [0x000e7] in <fa3055d36e9b44258d3aec143e6da8b4>:0 
    at JetBrains.ReSharper.Feature.Services.CodeCompletion.CombinedLookupItem.Accept (JetBrains.TextControl.ITextControl textControl, JetBrains.DocumentModel.DocumentRange nameRange, JetBrains.ReSharper.Feature.Services.Lookup.LookupItemInsertType insertType, JetBrains.ReSharper.Feature.Services.Lookup.Suffix suffix, JetBrains.ProjectModel.ISolution solution, System.Boolean keepCaretStill) [0x00068] in <fa3055d36e9b44258d3aec143e6da8b4>:0 
    at JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.LookupItems.LookupItemCompletor.CompleteItem (System.Action executeInsideCommandScope) [0x00111] in <fa3055d36e9b44258d3aec143e6da8b4>:0 
    at JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.LookupItems.LookupItemCompletor.CompleteItem () [0x00000] in <fa3055d36e9b44258d3aec143e6da8b4>:0 
    at JetBrains.ReSharper.Host.Features.Completion.CompletionHost.CompleteItem (JetBrains.ProjectModel.ISolution solution, JetBrains.Rider.Model.CompletionItem item, JetBrains.TextControl.ITextControl textControl, System.Nullable`1[T] completeChar) [0x0013e] in <4387d34e29d34db4b703d90cb49979f0>:0 
    at JetBrains.ReSharper.Host.Features.Completion.CompletionHost.HandleComplete (JetBrains.Rider.Model.CompleteData data, JetBrains.TextControl.ITextControl textControl) [0x00050] in <4387d34e29d34db4b703d90cb49979f0>:0
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “Generation is not available”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.LoggerBase.Log (JetBrains.Util.LoggingLevel level, System.String message, System.Exception ex) [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Util.Logging.LogEx.Error (JetBrains.Util.Logging.ILog this, System.Exception ex, System.String message) [0x00000] in <0e626f36971646f391be51717a3fc4b9>:0 
    at JetBrains.Util.Logging.Logger.LogException (System.Exception ex) [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.ReSharper.Host.Features.Completion.CompletionHost.HandleComplete (JetBrains.Rider.Model.CompleteData data, JetBrains.TextControl.ITextControl textControl) [0x00000] in <4387d34e29d34db4b703d90cb49979f0>:0 
    at JetBrains.ReSharper.Host.Features.Completion.CompletionHost+<>c__DisplayClass14_0.<CalculateItems>b__7 (JetBrains.Rider.Model.CompleteData completeData) [0x00000] in <4387d34e29d34db4b703d90cb49979f0>:0 
    at JetBrains.Platform.RdFramework.Tasks.RdEndpoint`2+<>c__DisplayClass26_0[TReq,TRes].<Set>b__0 (JetBrains.DataFlow.Lifetime lf, TReq req) [0x00000] in <a986200e347441c0b8879aab5034007d>:0 
    at JetBrains.Platform.RdFramework.Tasks.RdEndpoint`2+<>c__DisplayClass27_0[TReq,TRes].<Init>b__0 (JetBrains.Util.PersistentMap.UnsafeReader reader) [0x00000] in <a986200e347441c0b8879aab5034007d>:0 
    at JetBrains.Platform.RdFramework.Impl.MessageBroker.Execute (System.Action`1[T] handler, JetBrains.Platform.RdFramework.RdId id, System.Byte[] msg) [0x00000] in <a986200e347441c0b8879aab5034007d>:0 
    at JetBrains.Platform.RdFramework.Impl.MessageBroker+Subscription+<>c__DisplayClass5_0.<Invoke>b__0 () [0x00000] in <a986200e347441c0b8879aab5034007d>:0 
    at JetBrains.Threading.ReentrancyGuard.Execute (System.String name, System.Action action) [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Threading.ReentrancyGuard.ExecutePendingActions () [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Threading.JetDispatcher+Closure.Execute () [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Util.Concurrency.UnixJetDispatcher+UnixJetDispatcherStaticMethods.Run () [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Threading.JetDispatcher.Run () [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.ReSharper.Host.Product.ReSharperHostMain.Main (JetBrains.DataFlow.Lifetime lifetime, JetBrains.ReSharper.Host.Features.Settings.IReSharperHostSettings settings, JetBrains.Util.ILogger logger, JetBrains.ReSharper.Host.Features.Components.ShellProtocol protocol, JetBrains.Rider.Model.RdModelRoot modelRoot, JetBrains.Application.Environment.ApplicationShutdownRequests shutdownRequests) [0x00000] in <4387d34e29d34db4b703d90cb49979f0>:0 
    at System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod , System.Object , System.Object[] , System.Exception& ) [0x00000] in <981858f6b62c45ca83df98e2dc03c7d8>:0 
    at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <981858f6b62c45ca83df98e2dc03c7d8>:0 
    at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <981858f6b62c45ca83df98e2dc03c7d8>:0 
    at JetBrains.Application.Environment.RunsPublicStaticIntMain+<>c__DisplayClass0_0.<.ctor>b__0 () [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Util.Logging.Logger.Catch (System.Action action) [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Application.Threading.IThreadingEx+<>c__DisplayClass13_1.<ExecuteOrQueueWhenNotGuarded>b__2 () [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Threading.JetDispatcher+Closure.Execute () [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Util.Concurrency.UnixJetDispatcher+UnixJetDispatcherStaticMethods.Run (System.Func`1[TResult] condition, System.TimeSpan timeout, System.Boolean bThrowOnTimeout) [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Threading.JetDispatcher.Run (System.Func`1[TResult] condition, System.TimeSpan timeout, System.Boolean bThrowOnTimeout) [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Application.Environment.IJetHostEx.RunHostMessageLoop (JetBrains.Application.Components.IComponentContainer containerEnv) [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Application.Environment.HostParameters.MessagePumpMainLoopHostMixin.JetBrains.Application.Environment.HostParameters.IRunMainLoopHostMixin.RunMainLoop (JetBrains.Application.Components.ComponentContainer containerEnv) [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Application.Environment.HostParameters.JetHostParametersCaller.RunMainLoop (JetBrains.Application.Components.ComponentContainer containerEnv) [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Application.Environment.JetEnvironment.InternalRun (JetBrains.Application.Environment.HostParameters.JetHostParametersCaller host, JetBrains.Application.Components.ComponentContainer containerEnv) [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Application.Environment.JetEnvironment.CreateAndRun (JetBrains.Application.Environment.JetHostItems+Full hostparams) [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Application.Environment.JetHostItems.CreateAndRun (JetBrains.Application.Environment.JetHostItems+Full input) [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.ReSharper.Host.Product.ReSharperHostProgram.MainX (System.Reflection.Assembly assembly, JetBrains.Application.BuildScript.Application.HostInfo hostInfo, System.String[] args) [0x00000] in <4387d34e29d34db4b703d90cb49979f0>:0 
    at JetBrains.ReSharper.Host.Product.ReSharperHostProgram+<>c.<Main>b__0_0 (JetBrains.DataFlow.Lifetime lifetime) [0x00000] in <4387d34e29d34db4b703d90cb49979f0>:0 
    at JetBrains.DataFlow.Lifetimes.Using[TRetVal] (System.Func`2[T,TResult] λ) [0x00000] in <0e626f36971646f391be51717a3fc4b9>:0 
    at JetBrains.ReSharper.Host.Product.ReSharperHostProgram.Main () [0x00000] in <4387d34e29d34db4b703d90cb49979f0>:0
”

com.jetbrains.rider.util.idea.ReSharperHostException: Generation is not available

--- EXCEPTION #1/2 [AssertionException]
Message = “Generation is not available”
ExceptionPath = Root.InnerException
ClassName = JetBrains.Util.Assertion+AssertionException
HResult = COR_E_EXCEPTION=80131500
Source = JetBrains.Platform.RdCore
StackTraceString = “
  at JetBrains.Util.Assertion.Fail (System.String message) [0x00006] in <0e626f36971646f391be51717a3fc4b9>:0 
    at JetBrains.Util.Assertion.Assert (System.Boolean condition, System.String message) [0x00003] in <0e626f36971646f391be51717a3fc4b9>:0 
    at JetBrains.ReSharper.Feature.Services.Generate.Workflows.GenerateCodeWorkflowBase.ExecuteNonInteractive (System.String kind, JetBrains.ProjectModel.ISolution solution, JetBrains.TextControl.ITextControl textControl, JetBrains.ReSharper.Psi.PsiLanguageType languageType, JetBrains.Application.Progress.IProgressIndicator progress, System.Action`1[T] configureContext, System.Action`1[T] onCompleted) [0x00022] in <fa3055d36e9b44258d3aec143e6da8b4>:0 
    at JetBrains.ReSharper.Plugins.Unity.Feature.Services.CodeCompletion.UnityEventFunctionBehavior.Accept (JetBrains.TextControl.ITextControl textControl, JetBrains.DocumentModel.IRangeMarker rangeMarker, JetBrains.ProjectModel.ISolution solution) [0x00153] in <62d4493553c644dc94c24ad0acbef862>:0 
    at JetBrains.ReSharper.Plugins.Unity.Feature.Services.CodeCompletion.UnityEventFunctionBehavior.Accept (JetBrains.TextControl.ITextControl textControl, JetBrains.DocumentModel.DocumentRange nameRange, JetBrains.ReSharper.Feature.Services.Lookup.LookupItemInsertType lookupItemInsertType, JetBrains.ReSharper.Feature.Services.Lookup.Suffix suffix, JetBrains.ProjectModel.ISolution solution, System.Boolean keepCaretStill) [0x00007] in <62d4493553c644dc94c24ad0acbef862>:0 
    at JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.AspectLookupItems.BaseInfrastructure.LookupItem`1[TInfo].Accept (JetBrains.TextControl.ITextControl textControl, JetBrains.DocumentModel.DocumentRange nameRange, JetBrains.ReSharper.Feature.Services.Lookup.LookupItemInsertType insertType, JetBrains.ReSharper.Feature.Services.Lookup.Suffix suffix, JetBrains.ProjectModel.ISolution solution, System.Boolean keepCaretStill) [0x00006] in <fa3055d36e9b44258d3aec143e6da8b4>:0 
    at JetBrains.ReSharper.Feature.Services.CodeCompletion.CombinedLookupItem.CompleteItems (System.Collections.Generic.List`1[T] items, JetBrains.ReSharper.Psi.IPsiServices psiServices, JetBrains.TextControl.ITextControl textControl, JetBrains.DocumentModel.DocumentRange nameRange, JetBrains.ReSharper.Feature.Services.Lookup.LookupItemInsertType insertType, JetBrains.ReSharper.Feature.Services.Lookup.Suffix suffix, JetBrains.ProjectModel.ISolution solution, System.Boolean keepCaretStill, System.IDisposable batchTextChange) [0x000e7] in <fa3055d36e9b44258d3aec143e6da8b4>:0 
    at JetBrains.ReSharper.Feature.Services.CodeCompletion.CombinedLookupItem.Accept (JetBrains.TextControl.ITextControl textControl, JetBrains.DocumentModel.DocumentRange nameRange, JetBrains.ReSharper.Feature.Services.Lookup.LookupItemInsertType insertType, JetBrains.ReSharper.Feature.Services.Lookup.Suffix suffix, JetBrains.ProjectModel.ISolution solution, System.Boolean keepCaretStill) [0x00068] in <fa3055d36e9b44258d3aec143e6da8b4>:0 
    at JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.LookupItems.LookupItemCompletor.CompleteItem (System.Action executeInsideCommandScope) [0x00111] in <fa3055d36e9b44258d3aec143e6da8b4>:0 
    at JetBrains.ReSharper.Feature.Services.CodeCompletion.Infrastructure.LookupItems.LookupItemCompletor.CompleteItem () [0x00000] in <fa3055d36e9b44258d3aec143e6da8b4>:0 
    at JetBrains.ReSharper.Host.Features.Completion.CompletionHost.CompleteItem (JetBrains.ProjectModel.ISolution solution, JetBrains.Rider.Model.CompletionItem item, JetBrains.TextControl.ITextControl textControl, System.Nullable`1[T] completeChar) [0x0013e] in <4387d34e29d34db4b703d90cb49979f0>:0 
    at JetBrains.ReSharper.Host.Features.Completion.CompletionHost.HandleComplete (JetBrains.Rider.Model.CompleteData data, JetBrains.TextControl.ITextControl textControl) [0x00050] in <4387d34e29d34db4b703d90cb49979f0>:0
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “Generation is not available”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  at JetBrains.Util.LoggerBase.Log (JetBrains.Util.LoggingLevel level, System.String message, System.Exception ex) [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Util.Logging.LogEx.Error (JetBrains.Util.Logging.ILog this, System.Exception ex, System.String message) [0x00000] in <0e626f36971646f391be51717a3fc4b9>:0 
    at JetBrains.Util.Logging.Logger.LogException (System.Exception ex) [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.ReSharper.Host.Features.Completion.CompletionHost.HandleComplete (JetBrains.Rider.Model.CompleteData data, JetBrains.TextControl.ITextControl textControl) [0x00000] in <4387d34e29d34db4b703d90cb49979f0>:0 
    at JetBrains.ReSharper.Host.Features.Completion.CompletionHost+<>c__DisplayClass14_0.<CalculateItems>b__7 (JetBrains.Rider.Model.CompleteData completeData) [0x00000] in <4387d34e29d34db4b703d90cb49979f0>:0 
    at JetBrains.Platform.RdFramework.Tasks.RdEndpoint`2+<>c__DisplayClass26_0[TReq,TRes].<Set>b__0 (JetBrains.DataFlow.Lifetime lf, TReq req) [0x00000] in <a986200e347441c0b8879aab5034007d>:0 
    at JetBrains.Platform.RdFramework.Tasks.RdEndpoint`2+<>c__DisplayClass27_0[TReq,TRes].<Init>b__0 (JetBrains.Util.PersistentMap.UnsafeReader reader) [0x00000] in <a986200e347441c0b8879aab5034007d>:0 
    at JetBrains.Platform.RdFramework.Impl.MessageBroker.Execute (System.Action`1[T] handler, JetBrains.Platform.RdFramework.RdId id, System.Byte[] msg) [0x00000] in <a986200e347441c0b8879aab5034007d>:0 
    at JetBrains.Platform.RdFramework.Impl.MessageBroker+Subscription+<>c__DisplayClass5_0.<Invoke>b__0 () [0x00000] in <a986200e347441c0b8879aab5034007d>:0 
    at JetBrains.Threading.ReentrancyGuard.Execute (System.String name, System.Action action) [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Threading.ReentrancyGuard.ExecutePendingActions () [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Threading.JetDispatcher+Closure.Execute () [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Util.Concurrency.UnixJetDispatcher+UnixJetDispatcherStaticMethods.Run () [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Threading.JetDispatcher.Run () [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.ReSharper.Host.Product.ReSharperHostMain.Main (JetBrains.DataFlow.Lifetime lifetime, JetBrains.ReSharper.Host.Features.Settings.IReSharperHostSettings settings, JetBrains.Util.ILogger logger, JetBrains.ReSharper.Host.Features.Components.ShellProtocol protocol, JetBrains.Rider.Model.RdModelRoot modelRoot, JetBrains.Application.Environment.ApplicationShutdownRequests shutdownRequests) [0x00000] in <4387d34e29d34db4b703d90cb49979f0>:0 
    at System.Reflection.MonoMethod.InternalInvoke (System.Reflection.MonoMethod , System.Object , System.Object[] , System.Exception& ) [0x00000] in <981858f6b62c45ca83df98e2dc03c7d8>:0 
    at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <981858f6b62c45ca83df98e2dc03c7d8>:0 
    at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <981858f6b62c45ca83df98e2dc03c7d8>:0 
    at JetBrains.Application.Environment.RunsPublicStaticIntMain+<>c__DisplayClass0_0.<.ctor>b__0 () [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Util.Logging.Logger.Catch (System.Action action) [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Application.Threading.IThreadingEx+<>c__DisplayClass13_1.<ExecuteOrQueueWhenNotGuarded>b__2 () [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Threading.JetDispatcher+Closure.Execute () [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Util.Concurrency.UnixJetDispatcher+UnixJetDispatcherStaticMethods.Run (System.Func`1[TResult] condition, System.TimeSpan timeout, System.Boolean bThrowOnTimeout) [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Threading.JetDispatcher.Run (System.Func`1[TResult] condition, System.TimeSpan timeout, System.Boolean bThrowOnTimeout) [0x00000] in <3475087e88e040b3b9f097ffca9ad351>:0 
    at JetBrains.Application.Environment.IJetHostEx.RunHostMessageLoop (JetBrains.Application.Components.IComponentContainer containerEnv) [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Application.Environment.HostParameters.MessagePumpMainLoopHostMixin.JetBrains.Application.Environment.HostParameters.IRunMainLoopHostMixin.RunMainLoop (JetBrains.Application.Components.ComponentContainer containerEnv) [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Application.Environment.HostParameters.JetHostParametersCaller.RunMainLoop (JetBrains.Application.Components.ComponentContainer containerEnv) [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Application.Environment.JetEnvironment.InternalRun (JetBrains.Application.Environment.HostParameters.JetHostParametersCaller host, JetBrains.Application.Components.ComponentContainer containerEnv) [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Application.Environment.JetEnvironment.CreateAndRun (JetBrains.Application.Environment.JetHostItems+Full hostparams) [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.Application.Environment.JetHostItems.CreateAndRun (JetBrains.Application.Environment.JetHostItems+Full input) [0x00000] in <cd3596620f8d4217b396b4d513405503>:0 
    at JetBrains.ReSharper.Host.Product.ReSharperHostProgram.MainX (System.Reflection.Assembly assembly, JetBrains.Application.BuildScript.Application.HostInfo hostInfo, System.String[] args) [0x00000] in <4387d34e29d34db4b703d90cb49979f0>:0 
    at JetBrains.ReSharper.Host.Product.ReSharperHostProgram+<>c.<Main>b__0_0 (JetBrains.DataFlow.Lifetime lifetime) [0x00000] in <4387d34e29d34db4b703d90cb49979f0>:0 
    at JetBrains.DataFlow.Lifetimes.Using[TRetVal] (System.Func`2[T,TResult] λ) [0x00000] in <0e626f36971646f391be51717a3fc4b9>:0 
    at JetBrains.ReSharper.Host.Product.ReSharperHostProgram.Main () [0x00000] in <4387d34e29d34db4b703d90cb49979f0>:0
”

	at com.jetbrains.rider.protocol.components.LoggerHost$1.invoke(LoggerHost.kt:26)
	at com.jetbrains.rider.protocol.components.LoggerHost$1.invoke(LoggerHost.kt:15)
	at com.jetbrains.rider.util.reactive.Signal.fire(Signal.kt:29)
	at com.jetbrains.rider.framework.impl.RdSignal$2$1.invoke(RdSignal.kt:40)
	at com.jetbrains.rider.framework.impl.RdSignal$2$1.invoke(RdSignal.kt:15)
	at com.jetbrains.rider.framework.MessageBroker$Subscription$invoke$1.invoke(MessageBroker.kt:40)
	at com.jetbrains.rider.framework.MessageBroker$Subscription$invoke$1.invoke(MessageBroker.kt:25)
	at com.jetbrains.rider.protocol.RdDispatcher.pumpProtocolQueue(RdDispatcher.kt:62)
	at com.jetbrains.rider.protocol.IRdDispatcherKt.pumpProtocolQueue(IRdDispatcher.kt:17)
	at com.jetbrains.rider.util.idea.ExtensionsKt.syncFromBackendWithoutGateway(Extensions.kt:83)
	at com.jetbrains.rider.util.idea.ExtensionsKt.syncFromBackendWithoutGateway(Extensions.kt:68)
	at com.jetbrains.rider.util.idea.ExtensionsKt.syncFromBackend(Extensions.kt:62)
	at com.jetbrains.rider.completion.ReSharperLookupItem$syncBackendInsertion$changes$1.invoke(ReSharperLookupItem.kt:107)
	at com.jetbrains.rider.completion.ReSharperLookupItem$syncBackendInsertion$changes$1.invoke(ReSharperLookupItem.kt:33)
	at com.jetbrains.rider.util.idea.DocumentUtilKt.collectDocumentChanges(DocumentUtil.kt:79)
	at com.jetbrains.rider.completion.ReSharperLookupItem.syncBackendInsertion(ReSharperLookupItem.kt:100)
	at com.jetbrains.rider.completion.actions.RiderCodeCompletionHandler.a(RiderCodeCompletionHandler.kt:45)
	at com.jetbrains.rider.completion.actions.RiderCodeCompletionHandler.lookupItemSelected(RiderCodeCompletionHandler.kt:30)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.itemSelected(CompletionProgressIndicator.java:188)
	at com.intellij.codeInsight.completion.CompletionLookupArranger.itemSelected(CompletionLookupArranger.java:171)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.fireItemSelected(LookupImpl.java:859)
	at com.jetbrains.rider.completion.ReSharperLookup.fireItemSelected(ReSharperLookup.kt:128)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookupInWritableFile(LookupImpl.java:541)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.lambda$finishLookup$12(LookupImpl.java:498)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:141)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:498)
	at com.jetbrains.rider.completion.ReSharperLookup.finishLookup(ReSharperLookup.kt:118)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.finishLookup(LookupImpl.java:482)
	at com.intellij.codeInsight.lookup.impl.actions.ChooseItemAction$Handler.execute(ChooseItemAction.java:81)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doExecute(EditorActionHandler.java:173)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.lambda$execute$4(EditorActionHandler.java:207)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:110)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorAction.lambda$actionPerformed$0(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:107)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:86)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:618)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:667)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:666)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:521)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.g(IdeKeyEventDispatcher.java:476)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:213)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:738)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:434)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
</details>

**Comment by citizenmatt** [comment]
See also [RIDER-14147](https://youtrack.jetbrains.com/issue/RIDER-14147)
